language: python
python:
  "2.7"
install:
  "pip install --use-wheel -r src/config/requirements.txt"
script:
  "python src/manage.py test -v3"
env:
 - DJANGO_SETTINGS_MODULE=travis_settings PYTHONPATH=src
addons:
  postgresql: 9.3
