db:
  image: postgres:9.3
  environment:
    ## This password is obviously committed to version control. It would be
    ## ill-advised to use it on any accessible deployment (seriously).
    - POSTGRES_PASSWORD=T7mKAQOhMmo6hv0zOmm7
redis:
  image: redis:2.8
elasticsearch:
  image: elasticsearch
web:
  build: .
  command: bin/run-devserver.sh
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - redis
    - elasticsearch
