
# TODO: Split playbook into parts

- hosts: all

  tasks:

#
# Common tasks required to setup a new VM for use.
#

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=43200
      sudo: yes
      tags:
        - setup


#
# PostgreSQL install and setup
#

    - name: Install PostgreSQL
      apt:
        name: "{{item}}"
        state: present
      sudo: yes
      tags:
        - setup
      with_items:
        - postgresql
        - postgresql-contrib
        - postgresql-client
        - python-psycopg2 # Required by Ansible `postgresql_user` etc
