
# TODO: Split playbook into parts

- hosts: all


  # TODO: Handle password configuration better?
  # TODO: Don't use same password everywhere?
  vars_prompt:
    - name: password_avasecure
      prompt: "Enter avasecure user password"
      private: yes
      default: "insecure-NMYe_kX;8{m8J"
      tags:
        - setup


  tasks:

#
# Common tasks required to setup a new VM for use.
#

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=43200
      sudo: yes
      tags:
        - setup


#
# PostgreSQL install and setup
#

    - name: Install PostgreSQL
      apt:
        name: "{{item}}"
        state: present
      sudo: yes
      tags:
        - setup
      with_items:
        - postgresql
        - postgresql-contrib
        - postgresql-client
        - python-psycopg2 # Required by Ansible `postgresql_user` etc


    # TODO: Add other PG configuration changes from installation guide?

    - name: Configure PostgreSQL client authentication
      copy:
        src: files/pg_hba.conf
        dest: /etc/postgresql/9.3/main/pg_hba.conf
      sudo: yes
      tags:
        - setup
      notify: restart postgresql


    # TODO: Remove this when AVA setup is a separate task as
    #       in that case Ansible would automatically run handlers
    - meta: flush_handlers


    # TODO: Make these commands use TCP/IP rather than Unix sockets?
    - name: Create PostgreSQL AVA user
      postgresql_user:
        name: avasecure
        password: "{{password_avasecure}}"
      sudo: yes
      sudo_user: postgres
      tags:
        - setup

    - name: Create PostgreSQL AVA database
      postgresql_db:
        name: avadata
        owner: avasecure
      sudo: yes
      sudo_user: postgres
      tags:
        - setup


#
# Redis install and setup
#
    - name: Install Redis
      apt:
        name: "{{item}}"
        state: present
      sudo: yes
      tags:
        - setup
      with_items:
        - redis-server

    - name: Enable Unix socket connections for Redis
      # TODO: This assumes the default `redis.conf` file should we
      #       use `lineinfile` module instead?
      replace:
        dest: /etc/redis/redis.conf
        regexp: '^# (unixsocket)'
        replace: '\1'
      sudo: yes
      tags:
        - setup
      notify: restart redis-server


#
# RabbitMQ install and setup
#
    - name: Install RabbitMQ
      apt:
        name: "{{item}}"
        state: present
      sudo: yes
      tags:
        - setup
      with_items:
        - rabbitmq-server

    - name: Add RabbitMQ AVA virtual host
      rabbitmq_vhost:
        name: avatasks
      sudo: yes
      tags:
        - setup

    - name: Add RabbitMQ AVA user
      rabbitmq_user:
        user: avasecure
        password: "{{password_avasecure}}"
        vhost: avatasks
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      sudo: yes
      tags:
        - setup

#
# AVA Setup
#
# NOTE: This assumes that this playbook is being run from within the
#       AVA git repository.
#
# TODO: Add a variation that retrieves the source via git too?

    - name: Install AVA system dependencies
      apt:
        name: "{{item}}"
        state: present
      sudo: yes
      tags:
        - setup
      with_items:
        - python-pip
        - libpqxx-dev
        - python-dev
        - libldap2-dev
        - libsasl2-dev

    - name: Install AVA Python dependencies
      # TODO: Install the Ubuntu packaged versions instead?
      #       (This would avoid the system dependencies above and compilation.)
      pip:
        chdir: /home/vagrant/ava.github.com/ava
        requirements: config/requirements.txt
      sudo: yes



  handlers:

    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
      sudo: yes

    - name: restart redis-server
      service:
        name: redis-server
        state: restarted
      sudo: yes
