
# TODO: Split playbook into parts

- hosts: all


  # TODO: Handle password configuration better?
  vars_prompt:
    - name: dbpassword_avasecure
      prompt: "Enter avasecure user password"
      private: yes
      default: "insecure-NMYe_kX;8{m8J"
      tags:
        - setup


  tasks:

#
# Common tasks required to setup a new VM for use.
#

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=43200
      sudo: yes
      tags:
        - setup


#
# PostgreSQL install and setup
#

    - name: Install PostgreSQL
      apt:
        name: "{{item}}"
        state: present
      sudo: yes
      tags:
        - setup
      with_items:
        - postgresql
        - postgresql-contrib
        - postgresql-client
        - python-psycopg2 # Required by Ansible `postgresql_user` etc


    # TODO: Add other PG configuration changes from installation guide?

    - name: Configure PostgreSQL client authentication
      copy:
        src: files/pg_hba.conf
        dest: /etc/postgresql/9.3/main/pg_hba.conf
      sudo: yes
      notify: restart postgresql


    # TODO: Remove this when AVA setup is a separate task as
    #       in that case Ansible would automatically run handlers
    - meta: flush_handlers


  handlers:

    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
      sudo: yes
